server.port: 8888
spring.cloud.config.server.git.uri: https://github.com/zoouyong20/spring-cloud-config-demo.git
spring.cloud.config.server.git.searchPaths: /**
spring.cloud.config.server.git.username: 
spring.cloud.config.server.git.password:
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
spring.application.name: cloud-config-server